name: "Lyrics"
guid: "F4A1B2C3-D4E5-6F7A-8B9C-0D1E2F3A4B5C"
version: "1.5"
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "Felitendo"
overview: "Lyrics plugin with configurable search options and automatic library scanning"
description: >
  Lyrics plugin that downloads lyrics from lrclib.net with configurable search options

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Lyrics.dll"
changelog: |-
  ## v1.5.0.0
  ### What's New
  - Fixed support for Jellyfin 10.11
