name: Bug report
description: Report a reproducible problem in the plugin.
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect to happen?
      placeholder: Clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps so we can reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste relevant logs or stack traces.
      render: shell
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Jellyfin/plugin versions, OS, and any relevant setup details.
      placeholder: Jellyfin x.y.z, plugin x.y.z, OS ...
    validations:
      required: true
  - type: checkboxes
    id: duplicate-check
    attributes:
      label: Confirmation
      options:
        - label: I have checked that there is no duplicate issue.
          required: true
